### ISSUE TITLE
Feature request: unpublish multiple

### ISSUE THREAD

**Issue by hugovk** [frostming/legit#244]
The `git branches` and `git unpublish <branch>` commands are really useful.

It would be more useful if it would be possible to unpublish more than one branch:

```sh
git unpublish branch1 branch2 branch3
```

Would this be possible?

Thank you!

**Comment by weakish** [comment]
It is possible to implement this feature but I am a bit unsure about the API design.

Currently legit only supports `git unpublish foo`, then it is quite obvious `foo` is a branch name.

But what does `git unpublish foo bar` mean?

1. unpublish both foo and bar branch?
2. unpublish branch foo from bar remote?
3. (less likely) unpublish branch bar from foo remote?

Also, pr #242 may allow legit to specify remote as a command/verb argument.

Currently legit have neither "multiple branches" nor "multiple remote" concept.
I think we need to examine thoughtfully about whether and how to introduce these concepts.

**Comment by frostming** [comment]
This feature introduces ambiguity to the CLI API, hence I am -1 on this. Close it for now. Feel free to reopen if you have any better idea on this.
