### ISSUE TITLE
git switch

### ISSUE THREAD

**Issue by Hamuko** [frostming/legit#256]
[git v2.23 introduced a new command, _git switch_](https://github.com/git/git/blob/master/Documentation/RelNotes/2.23.0.txt#L61:L65). Seems like it's just an attempt to split up the current `checkout` command into more explicit commands, so it doesn't really do anything fancy (at least yet, it's advertised as experimental). However, there is quite a clear name conflict now with legit, as legit installs its own `switch` alias.

I imagine the best course would be for legit to rename its alias into something else. Another term or just opt with the shorthand `sw`.

**Comment by frostming** [comment]
Simply skip the alias for git >= 2.23.0, `git sw` is still available.
