### ISSUE TITLE
Windows 10 Defender idenity 1.0.1 relase as Trojan:Win32/Fuery.B!cl

### ISSUE THREAD

**Issue by vico93** [frostming/legit#257]
When i try to download the legit.exe from 1.0.1 release chrome stop downloading and Windows Defender warns about the file being malware.

Details in brazilian portuguese:
![image](https://user-images.githubusercontent.com/3485505/64745439-42335780-d4de-11e9-91fa-0768c750727a.png)

**Comment by vico93** [comment]
VirusTotal scan https://www.virustotal.com/gui/file/706bd588e571716642ecfc307b5b65e59c06f1507db774978e177959be74eb5b/detection

**Comment by frostming** [comment]
@vico93 I published 1.0.2 release, please try and see if the defender still claims virus.

**Comment by weakish** [comment]
Closed since this is outdated and there is no reply.
