### ISSUE TITLE
Status log output color same as background

### ISSUE THREAD

**Issue by streetdaddy** [frostming/legit#78]
I'm having some conflict between my terminal profile colors and the status_log output for legit commands.  For example, I can't see parts of the output for 'legit sync' - I can see the messages:

```
Pulling commits from the server.

Pushing commits to the server.
```

But not the other status message in between, because it seems that legit is using the same color for this text as the background color in my terminal profile colors.  If I change this particular color to something bright, I can then see the legit status_log output, but then in vim the background is that same bright color ... which is no good for me as I'm working with a dark terminal theme.

Looking through legit source, is it possibly this line that is causing this problem for me?  ie. using white() would solve my problem?  If so, is there a solution that will work for everyone, not just for me?

```
print black('\n'.join(out))
```

(https://github.com/kennethreitz/legit/blob/develop/legit/cli.py#L93)

**Comment by Oxicode** [comment]
gracias

**Comment by mbitokhov** [comment]
legit settings is outdated. now it's legit --config.

It doesn't seem like it works properly though. It launches vim and opens a file that just has the config file location. For me, it's `~/.config/legit/config.ini`. So just open it up with your favorite editor and change the value there
