### ISSUE TITLE
Build website with project repo included to build docs

### ISSUE THREAD

**Issue by patcon** [frostming/legit#84]
Was reading issue #37 and thought I'd chime in a feature suggestion to help keep docs coherent and up-to-date.

If docs in various places are getting out of sync, I might suggest taking the approach that composer went -- build the website using the docs in the project repo:
http://github.com/composer/getcomposer.org

Note that `composer.json` pulls in the `composer` project itself, just to access to docs dir, I believe. If you take that route, any pull request that changes features would be expected to be accompanied by the appropriate changes to the website :)

I personally find this approach _really_ clever, and am planning to use it on my own projects.

**Comment by wkentaro** [comment]
+1

**Comment by hickford** [comment]
Is http://www.git-legit.org/ open-source?

**Comment by wkentaro** [comment]
maybe the website is not open-source and maintained by @kennethreitz at present.
I think it should be in public if possible.

**Comment by wkentaro** [comment]
Some of the issues are caused by documentation not frequently updated.
* https://github.com/kennethreitz/legit/issues/61
* https://github.com/kennethreitz/legit/issues/65

**Comment by frostming** [comment]
Yeah, the docs are now included in project and the new home is https://frostming.github.io/legit
Welcome contributing!
